### ISSUE TITLE
Side bar is occluding the paper

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#31] opened 2020-02-03 02:08 UTC
One user reported to having to do horizontal scrolling to read the paper when the side bar was open. Others reported to it being annoying that parts of the paper couldn't be seen when the side bar was open. Users' difficulty dismissing the side bar probably makes this problem even more pronounced.

Potential solutions include:
* Just always having the sidebar open
* Shifting the PDF over to the left *and* zooming out of it so that its horizontal width has the same proportion to the available space (so that we guarantee the same amount parts of the paper will continue to be visible)

**Comment by zkirby** [comment] 2020-02-10 19:39
I personally feel option two is a better experience for a variety of reasons but primarily the potential clutter of option 1

**Comment by zkirby** [comment] 2020-02-10 19:41
I'll start working on trying to fix this with option 2

**Comment by andrewhead** [comment] 2020-02-10 20:09
I'm leaning that way as well! And good luck 👍

**Comment by zkirby** [comment] 2020-02-10 21:55
@andrewhead curious if you have any suggestions for dealing with the pdf.js API? The online resources I've found don't appear to be inclusive of all features of the API.

**Comment by zkirby** [comment] 2020-02-10 22:12
Deleted previous message, I have realized after playing around with the feel of this new feature as much as possible, the issue is not that the page needs to be zoomed out. The issue is that it can't be scrolled horizontally into view. Was actually a much easier fix than the zooming out issue

**Comment by andrewhead** [comment] 2020-02-11 00:24
@zkirby your work in #38 looks pretty good! Can you remind me the rationale for not zooming out when the side bar moves in? I am a bit nervous about hiding some sections of the paper that the user might have been looking at, either on the left side or the right side of the paper.

**Comment by zkirby** [comment] 2020-02-11 00:36
Yes, happy to discuss it in person in greater depth (I think if you see it, it will make more sense)! In essence, zooming out to a resolution that fits both the paper, the sidebar, and the drawer not only makes the text quite small but also feels jarring. I think it makes more sense to allow the user to zoom out or in to their desired font size on their own.

**Comment by andrewhead** [comment] 2020-02-11 17:17
Okay sounds good 👍 . Thank you for clarifying! I'll move this issue to "In Review". Can you give us a demo of this design during group meeting today?

**Comment by zkirby** [comment] 2020-03-17 20:11
Looks like I don't have the ability to close this issue, but it should probably be closed so we can declutter the issues list :)

**Comment by andrewhead** [comment] 2020-03-17 20:57
Good call!

**Closed** 2020-03-17 20:57 UTC
Labels: bug, high-priority, ui
